### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by prometheansacrifice** [hemanth/nmotw.in#27]
Can we have some installation instructions?

I assumed that it was a regular bundler project and ran `bundle install`. I ran into a couple of dependency issues, firstly with json 1.8.1. Luckily [this](http://stackoverflow.com/questions/29578142/how-to-install-json-gem-failed-to-build-gem-native-extensionmac-10-10) SO answer helped.

Next, I see the following when I do a `jekyll serve`

```
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring nokogiri-1.6.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.1
Ignoring posix-spawn-0.3.8 because its extensions are not built.  Try: gem pristine posix-spawn --version 0.3.8
Ignoring rdiscount-2.1.7.1 because its extensions are not built.  Try: gem pristine rdiscount --version 2.1.7.1
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0.5.0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Configuration file: /Users/prometheansacrifice/development/open-source/nmotw.in/_config.yml
       Deprecation: The 'plugins' configurationoption has been renamed to 'plugins_dir'. Please update your config file accordingly.
       Deprecation: The 'pygments' configuration option has been renamed to 'highlighter'. Please update your config file accordingly. The allowed values are 'rouge', 'pygments' or null.
/Users/prometheansacrifice/development/open-source/nmotw.in/plugins/pygments_code.rb:1:in `require': cannot load such file -- rb-pygments (LoadError)
        from /Users/prometheansacrifice/development/open-source/nmotw.in/plugins/pygments_code.rb:1:in `<top (required)>'
        from /Users/prometheansacrifice/development/open-source/nmotw.in/plugins/backtick_code_block.rb:1:in `require'
        from /Users/prometheansacrifice/development/open-source/nmotw.in/plugins/backtick_code_block.rb:1:in `<top (required)>'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `require'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `each'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `each'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/bin/jekyll:23:in `load'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/bin/jekyll:23:in `<main>'

```

And this too at some point in time (not any more weirdly)

```
Configuration file: /Users/prometheansacrifice/development/open-source/nmotw.in/_config.yml
       Deprecation: The 'plugins' configurationoption has been renamed to 'plugins_dir'. Please update your config file accordingly.
       Deprecation: The 'pygments' configuration option has been renamed to 'highlighter'. Please update your config file accordingly. The allowed values are 'rouge', 'pygments' or null.
/Users/prometheansacrifice/development/open-source/nmotw.in/plugins/pygments_code.rb:1:in `require': cannot load such file -- pygments (LoadError)
        from /Users/prometheansacrifice/development/open-source/nmotw.in/plugins/pygments_code.rb:1:in `<top (required)>'
        from /Users/prometheansacrifice/development/open-source/nmotw.in/plugins/backtick_code_block.rb:1:in `require'
        from /Users/prometheansacrifice/development/open-source/nmotw.in/plugins/backtick_code_block.rb:1:in `<top (required)>'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `require'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:75:in `block (2 levels) in require_plugin_files'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `each'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:74:in `block in require_plugin_files'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `each'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:73:in `require_plugin_files'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/plugin_manager.rb:18:in `conscientious_require'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/site.rb:97:in `setup'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/site.rb:49:in `initialize'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `new'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/commands/build.rb:30:in `process'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/lib/jekyll/commands/serve.rb:26:in `block (2 levels) in init_with_program'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `block in execute'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `each'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/command.rb:220:in `execute'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary/program.rb:42:in `go'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/mercenary-0.3.5/lib/mercenary.rb:19:in `program'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/gems/jekyll-3.0.1/bin/jekyll:17:in `<top (required)>'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/bin/jekyll:23:in `load'
        from /Users/prometheansacrifice/.rvm/gems/ruby-2.1.5/bin/jekyll:23:in `<main>'
```

Also the irony, NMOTW written using jekyll? :smile: Why not something like [wheat](https://github.com/creationix/wheat) that powers [howtonode.com](http://howtonode.org/)

**Comment by hemanth** [comment]
Sorry for the late reply.

Did you try `rake preview` ?

This is hosted on gh-pages so was on `jekyll ` will mostly migrate it to `ghost`
